version: '3.9'
services:
  nginx:
    container_name: yii2-shop_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports: 
      - "80:80"
      - "81:81"
      - "82:82"
      - "83:83"
    depends_on: 
      - mysql    
    volumes:
      - "./:/var/www/html"
    networks:
      - yii2-shop
  php:
    container_name: yii2-shop_php
    ports:
      - "9000:9000"
    networks:
      - yii2-shop
    build:
      context: ./docker/php
      dockerfile: Dockerfile
#      args:
#          UID: 1000
#          GID: 1000
    volumes:
        - "./:/var/www/html"
    links:
      - elasticsearch

  mysql:
    container_name: yii2-shop_mysql
    restart: always
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file: .env
    ports: 
      - '3365:3306'
    environment:
      - MYSQL_DATABASE=$shop_db
      - MYSQL_ROOT_PASSWORD=$shop_root_psswd
      - MYSQL_USER=$shop_user
      - MYSQL_PASSWORD=$shop_user_psswd
    networks:
      - yii2-shop
    volumes:
      - "db_data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yii2-shop_pma
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8888:80
    networks:
      - yii2-shop      
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - yii2-shop
    ports:
      - 9200:9200
  kibana:
    container_name: yii2-shop-kibana
    image: kibana:5.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - yii2-shop
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601      

  redis:
    image: redis:latest
    ports:
      - "6888:6379"
    networks:
      - yii2-shop
networks:
  yii2-shop:
    driver: bridge

volumes:
    db_data:
        driver: local